plugins {
    id 'java'
    id 'application'
}

mainClassName = "Main"

group 'com.killick.bots'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.2'
    testImplementation 'org.mockito:mockito-inline:3.7.7'
    testImplementation 'org.mockito:mockito-junit-jupiter:3.7.7'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.2'
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    implementation 'org.apache.commons:commons-configuration2:2.7'
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
    testLogging {
        events "passed", "skipped", "failed"
    }
}
jar {
    manifest {
        attributes 'Main-Class': 'Main'
    }
    /*
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
     */
}